spring.config.import=optional:file:.env[.properties]

gemini.api-key=${GEMINI_API_KEY}
gemini.embedding-model=${GEMINI_EMBEDDING_MODEL:gemini-embedding-001}

openrouter.api-key=${OPENROUTER_API_KEY}
openrouter.chat-model=${OPENROUTER_CHAT_MODEL:openrouter/free}

chroma.base-url=http://localhost:8000
chroma.collection=books_rag
